---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: nadiaabdelmoula
    password: nadia123456789

- name: Push the Docker image into the repo
  shell: docker push nadiaabdelmoula/devops:latest
